### ISSUE TITLE
Tortoisebot/Raspberry credentials

### ISSUE THREAD

**Issue by KarthiAru** [rigbetellabs/tortoisebot#18]
Hi! I got my tortoisebot today and I've reached the step where I got the bot connected to wifi. Now, how do I connect to it from my ubuntu laptop? What are the credentials to connect via VNC or ssh?

**Comment by Ashish080213** [comment]
@KarthiAru try login id: tortoisebot   password: raspberry

**Comment by KarthiAru** [comment]
I updated the sshd_config file to enable public-key authentication instead of password authentication. I also installed tightvnc on raspberry to connect from the laptop.

**Comment by Ashish080213** [comment]
@KarthiAru Did you try RealVNC Viewer?

**Comment by KarthiAru** [comment]
> @KarthiAru Did you try RealVNC Viewer?

Yes, I used the realvnc client from the laptop

**Comment by Ashish080213** [comment]
@KarthiAru Did you try that without using any HDMI cable? if yes then are you able to use realvnc without any error? I have an issue that its showing "Cannot currently show the display".
But if I connect the raspi to the monitor using HDMI cable and if I connect realvnc using my laptop its working fine.

**Comment by Ashish080213** [comment]
what OS are you using in raspi?

**Comment by KarthiAru** [comment]
> what OS are you using in raspi?

Ubuntu 20.04

**Comment by KarthiAru** [comment]
> @KarthiAru Did you try that without using any HDMI cable? if yes then are you able to use realvnc without any error? I have an issue that its showing "Cannot currently show the display". But if I connect the raspi to the monitor using HDMI cable and if I connect realvnc using my laptop its working fine.

Yes, I'm able to view the raspi desktop without issues. I didn't use any HDMI cables.

These are the steps I followed to set it up.

0. Update VNC server settings
```
tortoisebot@ubuntu:~/.vnc$ pwd
/home/tortoisebot/.vnc
tortoisebot@ubuntu:~/.vnc$ sudo nano xstartup
```

```
#!/bin/sh
unset SESSION_MANAGER
unset DBUS_SESSION_BUS_ADDRESS
startxfce4 &

[ -x /etc/vnc/xstartup ] && exec /etc/vnc/xstartup
[ -r $HOME/.Xresources ] && xrdb $HOME/.Xresources
xsetroot -solid grey
vncconfig -iconic &

```

1. Start VNC server
```
tortoisebot@ubuntu:~$ tightvncserver
New 'X' desktop is ubuntu:2
Starting applications specified in /home/tortoisebot/.vnc/xstartup
Log file is /home/tortoisebot/.vnc/ubuntu:2.log
```

2. SSH connection with port forwarding in a new terminal
`ssh -L 5902:localhost:5902 -vNC tortoisebot@192.168.0.123`

If New 'X' desktop is ubuntu:1, then port is 5901
If New 'X' desktop is ubuntu:2, then port is 5902 and so on

3. Open the VNC client and connect to server using
localhost:5902

**Comment by Ashish080213** [comment]
@KarthiAru followed all the steps but its showing blank screen 
![Screenshot from 2024-04-20 17-55-35](https://github.com/rigbetellabs/tortoisebot/assets/92209111/94b9892c-430d-46e7-94ae-a3a90b3e002b)
