### ISSUE TITLE
Cannot Login into Tortoisebot

### ISSUE THREAD

**Issue by UdaySMukherjee** [rigbetellabs/tortoisebot#22]
I installed The image from
https://drive.google.com/drive/folders/1DolvF8kghl2Gsx-hII6o5sz88YTQxJYI

but now on boot its showing username rigbetellabs
when i enter password as tortoisebot 
it gives error as 'sorry, it didnt worked'

**Comment by ShubhamNandi** [comment]
so the password is "raspberry" It is mentioned in the wiki [Raspberry Pi Password](https://github.com/rigbetellabs/tortoisebot/wiki/5.-ROS2#6-real-robot)
