### ISSUE TITLE
Lagging 

### ISSUE THREAD

**Issue by nd013** [rigbetellabs/tortoisebot#5]
I am working with rplidar instead of ydlidar and Accordingly I changed ydliar_ros to rplidar_ros package. Also through HDMI cable I can able to run bringup.launch
But when I tried to launch bringup.launch through ssh, my ssh terminal was lagged. On removing lidar the terminal works. What should I do?

**Comment by ShubhamNandi** [comment]
Firstly is check your network secondly how are using the lidar and its node please provide details on that as well!
