### ISSUE TITLE
Autonomous navigation is not working

### ISSUE THREAD

**Issue by a2a4** [rigbetellabs/tortoisebot#7]
Hey Rigibetel labs team,

When I tried to make the motors move, using teleop in tortoisebot_control package. The robot simply starts moving forward when I do the rosrun the script. It doesnot stop. How to solve this??

**Comment by ShubhamNandi** [comment]
you can use the teleop_twist_keyboard pkg and its respective cmds to move and stop the robot 
if there are further issues do let us know
